[package]
name = "auth_server"
version = "0.1.0"
edition = "2021"

[dependencies]
arc = "0.0.1"
mutex = "0.1.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42.0", features = ["full"] }
